# Generated by Django 5.1.3 on 2025-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="price",
        ),
        migrations.AddField(
            model_name="facility",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
