# Generated by Django 5.1.3 on 2025-05-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0002_remove_facility_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="settled",
            field=models.BooleanField(default=False),
        ),
    ]
