# Generated by Django 5.1.3 on 2025-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0003_booking_settled"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
