# Generated by Django 5.1.3 on 2024-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_user_delete_roomservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
