# Generated by Django 5.1.3 on 2024-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_roomservicerequest_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('room_service', 'Room Service'), ('laundry', 'Laundry'), ('cleaning', 'Cleaning')], max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
