# Generated by Django 5.1.3 on 2024-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_serviceavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservicerequest',
            name='service_type',
            field=models.CharField(choices=[('room cleaning', 'Room Cleaning'), ('change sheets', 'Change sheets'), ('washroom cleaning', 'Clean washroom'), ('waterbottles', 'Water Bottles'), ('toileteries', 'Toileteries'), ('cutlery', 'Cutlery'), ('electrical repair', 'Electrical Repairs'), ('plumbing repair', 'Plumbing Repairs'), ('room service', 'Request attendant'), ('SOS', 'SOS'), ('checkout', 'Checkout')], max_length=20),
        ),
    ]
