# Generated by Django 5.1.3 on 2025-05-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_alter_roomservicerequest_service_type"),
        ("core", "0002_servicetype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceAvailability",
        ),
        migrations.AlterField(
            model_name="roomservicerequest",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.servicetype"
            ),
        ),
    ]
