# Generated by Django 5.1.3 on 2025-05-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_delete_serviceavailability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomservicerequest",
            name="room_settled",
            field=models.BooleanField(default=False),
        ),
    ]
