# Generated by Django 5.1.3 on 2025-05-12 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_percentage",
                    models.FloatField(
                        default=0.0, help_text="Global tax percentage for the user."
                    ),
                ),
                (
                    "additional_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Any additional service charge.",
                        max_digits=6,
                    ),
                ),
                (
                    "is_menu_available",
                    models.BooleanField(
                        default=True, help_text="Toggle to show/hide the menu."
                    ),
                ),
                (
                    "is_service_available",
                    models.BooleanField(
                        default=True, help_text="Toggle to enable/disable room service."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
