# Generated by Django 5.1.3 on 2025-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_servicetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
