# Generated by Django 5.1.3 on 2025-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_menuitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="discount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
