# Generated by Django 5.1.3 on 2025-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_category_menuitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="discounted_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
