# Generated by Django 5.1.3 on 2025-05-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0007_table_order_table"),
        ("rooms", "0004_room_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.room",
            ),
        ),
    ]
