# Generated by Django 5.1.3 on 2025-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0008_alter_order_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="settled",
            field=models.BooleanField(default=False),
        ),
    ]
