# Generated by Django 5.1.3 on 2025-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0009_order_settled"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="empty",
            field=models.BooleanField(default=True),
        ),
    ]
