# Generated by Django 5.1.3 on 2025-05-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0010_table_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="room_settled",
            field=models.BooleanField(default=False),
        ),
    ]
